---
#- hosts: master
#  become: yes
#  become_method: sudo
#  tags:
#  - helm
#  tasks:

- set_fact:
    env_kc: '{{ proxy_env |default({}) | combine ({"PATH" : "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin"  }) | combine ({"KUBECONFIG" :"/etc/kubernetes/admin.conf"}) }}'
  tags:
  - always

- block:
  - name: 'Download {{ helm.install_script_url | default ("https://github.com/kubernetes/helm/raw/master/scripts/get-helm-3") }}'
    #environment: '{{ proxy_env | default ({}) }}'
    environment: '{{env_kc}}'
    get_url: url={{ helm.install_script_url | default ("https://github.com/kubernetes/helm/raw/master/scripts/get-helm-3") }} dest=/tmp/helm_install_script force=yes mode="0755"
    when: helm is defined

  - name: 'Download "https://github.com/kubernetes/helm/raw/master/scripts/get-helm-3" '
    environment: '{{ proxy_env | default ({}) }}'
    get_url: url="https://github.com/kubernetes/helm/raw/master/scripts/get-helm-3" dest=/tmp/helm_install_script force=yes mode="0755"
    when: helm is not defined

  - name: Run /tmp/helm_install_script
    environment: '{{env_kc}}'
    shell: "/tmp/helm_install_script --version {{helm.helm_version | default ('latest')}}"
    register: command_result
    changed_when: '"is up-to-date" not in command_result.stdout'
    when: helm is defined
    args:
      chdir: /tmp/

  - name: Run /tmp/helm_install_script
    environment: '{{env_kc}}'
    shell: "/tmp/helm_install_script --version latest "
    register: command_result
    changed_when: '"is up-to-date" not in command_result.stdout'
    when: helm is not defined
    args:
      chdir: /tmp/

  - name: helm completion shell
    environment: '{{env_kc}}'
    shell: helm completion {{ shell | default ('bash') }} > ~/.kube/helm_completion.bash.inc
    args:
      warn: no

  - name: helm completion to ~/.bashrc
    lineinfile:
      dest: ~/.bashrc
      line: '[[ -n $PS1 ]] && [[ -x ${HOME}/.kube/helm_completion.bash.inc ]] && source ${HOME}/.kube/helm_completion.bash.inc'
      state: present
    when: shell is undefined or shell == 'bash'

  - name: helm repo add 
    environment: '{{env_kc}}'
    command: helm repo add {{ item.name }} {{ item.url }}
    with_items: 
    - '{{ helm.repos | default("") }}'
    when: helm is defined and helm.repos is defined

  - name: helm repo update #Sometimes initial repo add corrupts the repo and update fixes it.
    environment: '{{env_kc}}'
    command: helm repo update
    when: helm is defined

  tags:
  - helm

