---
- name: kubectl and helm aliases to ~/.bashrc (if exists)
  lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
    state: present
    create: no
  ignore_errors: yes
  with_items:
  - "alias watch='watch ' "
  - "alias k='kubectl ' "
  - "alias kk='kubectl -o wide --show-labels '"
  - "alias ks='kubectl -n kube-system ' "
  - "alias hs='helm --namespace kube-system ' "
  - "alias km='kubectl -n monitoring ' "
  - "alias hm='helm --namespace monitoring ' "
  - "alias kg='kubectl get --all-namespaces -o wide '" # --show-labels '"
  - "alias hg='helm list --all --all-namespaces --pending '"
  - "alias kgl='kubectl get --all-namespaces -o wide --show-labels '"
  - "alias kgp='kubectl get --all-namespaces -o wide --show-labels po'"
  - "alias wp='watch kg po '" # -w --show-labels '"
  - "alias wipt='watch -n1 iptables -vnL ' "

- name: kubectl aliases to ~/.zshrc (if exists)
  lineinfile:
    dest: ~/.zshrc
    line: "{{ item }}"
    state: present
    create: no
  ignore_errors: yes
  with_items:
  - "alias watch='watch ' "
  - "alias k='kubectl ' "
  - "alias kk='kubectl -o wide --show-labels '"
  - "alias ks='kubectl -n kube-system ' "
  - "alias hs='helm --namespace kube-system ' "
  - "alias km='kubectl -n monitoring ' "
  - "alias hm='helm --namespace monitoring ' "
  - "alias kg='kubectl get --all-namespaces -o wide '" # --show-labels '"
  - "alias hg='helm list --all --all-namespaces --pending '"
  - "alias kgl='kubectl get --all-namespaces -o wide --show-labels '"
  - "alias kgp='kubectl get --all-namespaces -o wide --show-labels po'"
  - "alias wp='watch kg po '" # -w --show-labels '"
  - "alias wipt='watch -n1 iptables -vnL ' "
  
- name: Install optional packages like bash-completion
  package: name={{ item }} state={{ package_state | default ('present') }}
  with_items:
  - bash-completion
  ignore_errors: yes

- name: add kubectl/kubeadm/helm shell competions to ~/.bashrc (if exists)
  lineinfile:
    dest: ~/.bashrc
    line: "{{ item }}"
    state: present
    create: no
  ignore_errors: yes
  with_items:
  - "[[ -n $PS1 ]] && source <(kubectl completion bash 2>/dev/null || true)"
  - "[[ -n $PS1 ]] && source <(kubeadm completion bash 2>/dev/null || true)"
  - "[[ -n $PS1 ]] && source <(helm    completion bash 2>/dev/null || true)"

- name: add completion to kubectl aliases in ~/.bashrc (if exists)
  lineinfile:
    dest: ~/.bashrc
    line: ""[[ -n $PS1 ]] && complete -F __start_kubectl {{ item }}"
    state: present
    create: no
  ignore_errors: yes
  with_items:
  - k
  - ks
  - km
  - kg

- name: add completion to helm aliases in ~/.bashrc (if exists)
  lineinfile:
    dest: ~/.bashrc
    line: ""[[ -n $PS1 ]] && complete -F __start_helm {{ item }}"
    state: present
    create: no
  ignore_errors: yes
  with_items:
  - hs
  - hm
  - hg

## SAME for ZSH:
- name: add kubectl/kubeadm/helm shell competions to ~/.zshrc (if exists)
  lineinfile:
    dest: ~/.zshrc
    line: "{{ item }}"
    state: present
    create: no
  ignore_errors: yes
  with_items:
  - "# k8s shell completion; for zsh min vers is 5.2+"
  - "[[ -n $PS1 ]] && source <(kubectl completion zsh 2>/dev/null || true)"
  - "[[ -n $PS1 ]] && source <(kubeadm completion zsh 2>/dev/null || true)"
  - "[[ -n $PS1 ]] && source <(helm    completion zsh 2>/dev/null || true)"

- name: add completion to kubectl aliases in ~/.zshrc (if exists)
  lineinfile:
    dest: ~/.zshrc
    line: ""[[ -n $PS1 ]] && compdef __start_kubectl {{ item }}"
    state: present
    create: no
  ignore_errors: yes
  with_items:
  - k
  - ks
  - km
  - kg

- name: add completion to helm aliases in ~/.zshrc (if exists)
  lineinfile:
    dest: ~/.zshrc
    line: ""[[ -n $PS1 ]] && compdef __start_helm {{ item }}"
    state: present
    create: no
  ignore_errors: yes
  with_items:
  - hs
  - hm
  - hg
